// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0rR0SzQ9DkyWxK8GwNUI5FEg7I0_wZWA',
    appId: '1:315129263820:web:23a317c7d7bbff9f7a7469',
    messagingSenderId: '315129263820',
    projectId: 'marketplace-codingstore',
    authDomain: 'marketplace-codingstore.firebaseapp.com',
    storageBucket: 'marketplace-codingstore.firebasestorage.app',
    measurementId: 'G-EDTFFJ6KEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3FLwgUQn5KEJuiA15FGPPaul0sKUZm0',
    appId: '1:315129263820:android:0737667a33ae035e7a7469',
    messagingSenderId: '315129263820',
    projectId: 'marketplace-codingstore',
    storageBucket: 'marketplace-codingstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8hlSaaacWEnJwy175T-XZVWRxL4ts-0',
    appId: '1:315129263820:ios:0b74bcb98379327b7a7469',
    messagingSenderId: '315129263820',
    projectId: 'marketplace-codingstore',
    storageBucket: 'marketplace-codingstore.firebasestorage.app',
    iosBundleId: 'com.example.evanMachineStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8hlSaaacWEnJwy175T-XZVWRxL4ts-0',
    appId: '1:315129263820:ios:0b74bcb98379327b7a7469',
    messagingSenderId: '315129263820',
    projectId: 'marketplace-codingstore',
    storageBucket: 'marketplace-codingstore.firebasestorage.app',
    iosBundleId: 'com.example.evanMachineStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0rR0SzQ9DkyWxK8GwNUI5FEg7I0_wZWA',
    appId: '1:315129263820:web:ec821570fb469a2c7a7469',
    messagingSenderId: '315129263820',
    projectId: 'marketplace-codingstore',
    authDomain: 'marketplace-codingstore.firebaseapp.com',
    storageBucket: 'marketplace-codingstore.firebasestorage.app',
    measurementId: 'G-HVWXRQJ2GV',
  );
}
